import React, { useState, useEffect, useContext } from 'react';
import Head from 'next/head'
import Image from "next/image";
import Login from '../components/Login/Login'
import Home from '../components/Home/Home';
import Index from '../components/Index/Index';
import { firestore, storage } from "../config.firebase";
import firebase from "../config.firebase";

export default function HomePage({logo, firebase, firestore, userFirebase, user, handleUser}) {
  //const [user, setUser] = useUserContext();
  //const { state, userReducer } = useAppContext();
  //console.log("STATE ++++++++", state);
  //console.log("USER_REDUCER ++++++++", userReducer);
/*
  const handleUser = (pUser) => {
    setUser(pUser);
  }
  */
console.log("CUSTOM KEY", process.env.customKey)
  
  //const auth = firebase.auth();
  //console.log("AUTH index", auth);
  const [content, setContent] = useState(<></>);

  useEffect(() => {

    console.log("userFirebase +++++++", userFirebase);
    console.log("user ++++++++", user);
  }, [user]);

  return (
    <Index logo={logo} firebase={firebase} firestore={firestore} user={user} handleUser={handleUser} />

    /*
        <Home logo={logo} firebase={firebase} firestore={firestore} userFirebase={userFirebase} handleUserFirebase={handleUserFirebase} handleUser={handleUser} />


    <Login logo={logo} firebase={firebase} firestore={firestore} handleUser={handleUser} />


<div className={styles.container}>
      <Menu firebase={firebase} />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    */
  )
}

/*
// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://.../data`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}
*/