import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from "next/image";
import Profile from '../components/Profile/Profile';
import Menu from '../components/Account/Menu';


export default function ProfilePage({logo, user, firebase, firestore, storage, userFirebase, handleUserFirebase, handleUser, auth, dashboard, screenMode}) {
    return(
        <Menu pages={{ profile: true, }} title={"Profile"} firebase={firebase} user={user}>
             <Head>
            <title>Dandela Web App - Profile</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
            <Profile logo={logo} user={user} handleUser={handleUser} firebase={firebase} firestore={firestore} storage={storage} userFirebase={userFirebase} handleUserFirebase={handleUserFirebase} />
        </Menu>
    )
}