import React, { useState, useEffect } from 'react';
//import useTranslation from 'next-translate/useTranslation';
import Head from 'next/head'
import Profile from '../components/Profile/Profile';
import Dashboard from '../components/Dashboard/Dashboard';
import { useUserContext } from '../context/UserProvider';
import InstallApp from '../components/InstallApp/InstallApp';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'next-i18next'
import { Button } from '@mui/material';
import { US, GB, FR, PT } from 'country-flag-icons/react/3x2'

export default function ProfilPage({ logo, user, firebase, firestore, storage, userFirebase, handleUserFirebase, handleUser, auth, dashboard, screenMode}) {
  const { t, i18n } = useTranslation('common')
console.log("TRANSLATE", t('profil'))
const onChangeLanguage = (language) => {
  i18n.changeLanguage(language);
};

  return(
        <Dashboard pages={{ profile: true, }} title={t('profil')} firebase={firebase} user={user} storage={storage}>
             <Head>
            <title>Dandela Web App - Profile</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <FR onClick={() => {
            onChangeLanguage('fr');
          }} title="Français" className="..." width={'50px'} height={'50px'} style={{cursor: 'pointer', marginRight:5}}  />
          <GB onClick={() => {
            onChangeLanguage('en');
          }} title="Anglais" className="..." width={'50px'} height={'50px'} style={{cursor: 'pointer', marginRight:5}}  />
          <PT onClick={() => {
            onChangeLanguage('pt');
          }} title="Portugais" className="..." width={'50px'} height={'50px'} style={{cursor: 'pointer', marginRight:5}}  />
          <Button onClick={() => {
            onChangeLanguage('en');
          }}>Change langue</Button>
          <Profile logo={logo} user={user} handleUser={handleUser} firebase={firebase} firestore={firestore} storage={storage} userFirebase={userFirebase} handleUserFirebase={handleUserFirebase} />
        </Dashboard>
    )
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, [
        'common',
        //'footer',
      ], null, ['en', 'fr', 'pt'])),
      // Will be passed to the page component as props
    },
  }
}